#!/usr/bin/env python3
from typing import NamedTuple, List, Any, Iterable, Tuple, Optional

from my.hypothesis import get_pages # type: ignore

from kython.org_tools import link as org_link

from org_view import OrgView
from org_utils import OrgTree, as_org

class HypView(OrgView):
    def make_tree(self) -> OrgTree:
        return OrgTree(
            f"# AUTOGENERATED BY {__file__}\n", # TODO date?
            [
                OrgTree(
                    as_org(
                        created=page.dt,
                        heading=org_link(title=page.title, url=page.link),
                    ),
                    [
                        OrgTree(as_org(
                            created=hl.dt,
                            heading=org_link(title='hyp', url=hl.hyp_link),
                            body=hl.content,
                        )) for hl in page.highlights
                    ]
                ) for page in get_pages()
            ]
        )


# TODO tests for determinism

def main():
    HypView(
        logger_tag='hypothesis-view',
        default_to='hypothesis.org',
    ).main()
    # TODO need to group by source??

if __name__ == '__main__':
    main()
