#!/usr/bin/env python3
from typing import NamedTuple, List, Any, Iterable, Tuple, Optional, Collection

from my.reddit import get_saves # type: ignore

from kython.org_tools import link as org_link

from org_view import OrgViewAppend, OrgWithKey
from org_utils import OrgTree, as_org

# TODO mm, yeah, perhaps favoriting date makes a bit more sense...
# TODO FIXME show deleted somehow
# I guess, sort of reasonable to test at rendering time

# TODO actually might be useful to store forever a read only version...

class RedditView(OrgViewAppend):
    def get_items(self) -> Collection[OrgWithKey]:
        return [(
            f.sid,
            OrgTree(as_org(
                    created=f.dt,
                    heading=org_link(title=f.title, url=f.url) + f' /r/{f.subreddit}',
                    body=f.text,
            ))
        ) for f in get_saves(all_=False)] # TODO FIXME need all!


def main():
    RedditView(
        logger_tag='reddit-view',
        file_header=f"# AUTOGENERATED BY {__file__}",
    ).main(
        default_to='reddit.org',
        default_state='reddit.json',
    )

if __name__ == '__main__':
    main()

# ok, so far:
# adding -- tracked via json state; kinda ok.
# hmmm! just keep reddit bookmarks intact! whatever, serously!
# one reason for using reddit ('native') favoriting is that you get more metadata for free
# hypothesis and instapaper views do not update state and clear the file before writing
# reddit view tracks the state and appends only
