#!/usr/bin/env python3
from typing import NamedTuple, List, Any, Iterable, Tuple, Optional

from my.reddit import get_saves # type: ignore

from kython.org_tools import link as org_link

from org_view import OrgView
from org_utils import OrgTree, as_org

# TODO mm, yeah, perhaps favoriting date makes a bit more sense...
# TODO show deleted somehow
# TODO sanitize bodies
class RedditView(OrgView):
    def make_tree(self) -> OrgTree:
        return OrgTree(
            f"# AUTOGENERATED BY {__file__}\n",
            [
                OrgTree(as_org(
                    created=f.dt,
                    heading=org_link(title=f.title, url=f.url),
                    body=f.text,
                )) for f in get_saves(all_=False)
            ]
        )


def main():
    RedditView(
        logger_tag='reddit-view',
        default_to='reddit.org',
    ).main()

if __name__ == '__main__':
    main()
